name = "cv-hugo-theme"
license = "Apache-2.0"
licenselink = "https://github.com/jamespoulin007/cv-hugo-theme/blob/main/LICENSE"
description = "A simple hugo theme for CV"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/jamespoulin007/cv-hugo-theme"

# If you have a running demo of the theme.
# demosite = "https://.github.io/"

tags = [
  "Portfolio",
  "Blog",
  "Resume",
  "Projects",
  "Gallery",
  "Multilingual",
  "Minimalist",
  "Responsive",
  "Customizable",
  "Google analytics",
  "Disqus",
  "Bootstrap",
  "Syntax highlighting",
]
features = [
  "Minimalist Design",
  "Fully Responsive",
  "Multiple Language Support",
  "Carefully Designed Cards",
  "Experience Timeline",
  "Achievement Gallery",
  "Sidebar to Categorize the Posts",
  "Short Codes",
  "Google Analytics Support",
  "Disqus Comment Support",
]

[author]
  # homepage = "https://github.io"
  name = "James Poulin"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.128.0"